apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: certmanager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${acmeEmail}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
            - "aws.paasify.org"
      dns01:
        route53:
          region: us-west-2
          accessKeyID: ${accessKey}
          secretAccessKeySecretRef:
            name: aws-iam
            key: secret_access_key